---
- name: Download SQL Operations Studio
  shell: wget {{ sql_ops_url_deb }}

- name: Install SQL Operations Studio
  become: true
  apt:
    deb: '{{ sql_ops_filename }}'

- name: Remove downloaded file
  become: true
  shell: rm '{{ sql_ops_filename }}' 