---
- name: Download vagrant
  shell: wget {{ vagrant_url_deb }}

- name: Install vagrant for Debian OS family
  become: true
  shell: gdebi -n vagrant_{{vagrant_version}}_x86_64.deb

- name: Install reload plugin
  shell: vagrant plugin install vagrant-reload

- name: Remove downloaded file
  shell: rm vagrant_{{vagrant_version}}_x86_64.deb