---
- name: Create git folder
  file:
    path: $HOME/git
    state: directory

- name: Clone git repos
  git:
    repo: https://github.com/markgaze/{{ item }}
    dest: $HOME/git/markgaze/{{ item }}
    force: no
    update: yes
  with_items: "{{git_repos}}"