---
- name: Install nodejs
  become: true
  pacman:
    name: nodejs
    state: latest

- name: Install npm
  become: true
  pacman:
    name: npm
    state: latest

- name: Install node packages
  become: true
  npm:
    name: "{{ item }}"
    global: yes
    state: latest
  with_items: "{{node_packages}}"

- name: Install node packages with unsafe-perm
  become: true
  command: "npm install -g {{ item }} --unsafe-perm"
  with_items: "{{ unsafe_node_packages }}"
