---
# - name: Get best pacman mirrors
#   become: true
#   shell: pacman-mirrors --fasttrack

# - name: Update pacman cache
#   become: true
#   pacman:
#     update_cache: yes
#     upgrade: yes

- name: Install pacman packages
  become: true
  pacman:
    name: "{{ item }}"
    state: latest
  with_items: "{{pacman_packages}}"