---
- name: Create apps folder
  file:
    path: $HOME/git/apps
    state: directory
    mode: 0755

- name: Clone git repos
  git:
    repo: https://github.com/markgaze/{{ item }}
    dest: $HOME/git/apps/{{ item }}
    force: no
    update: no
  with_items: "{{git_repos}}"