---
- name: Install gdebi
  apt:
    name: gdebi
    state: latest

- name: Download hyper.js deb file
  shell: wget https://releases.hyper.is/download/deb

- name: Install hyper.js
  shell: gdebi -n linux_deb