---
apt_packages:
  - bash-completion
  - docker.io
  - git
  - curl
  - wget
  - vim
  - cowsay
  - virtualbox
  - virtualbox-ext-pack
  - virtualbox-qt
  - libgconf2-4
  - unrar

node_packages:

git_repos:
  - dotfiles

vagrant_version: "2.1.2"
vagrant_url_deb: "https://releases.hashicorp.com/vagrant/{{vagrant_version}}/vagrant_{{vagrant_version}}_x86_64.deb"