name: Checks
on: [push]

jobs:
  checks:
    name: Run checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    
    - name: Install
      run: |
        npm install

    - name: Run vet
      run: |
        npm run vet
